// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Auth } from '@angular/fire/auth';
import { User } from 'firebase/auth';
import { Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { StoryDialogComponent } from '../story-dialog/story-dialog.component';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {
  isDarkMode = false;
  dropdownOpen = false;
  user: User | null = null;
  userProfile: any = null;

  constructor(
    private authService: AuthService,
    private auth: Auth,
    private router: Router,
    private dialog: MatDialog,
    private userService: UserService
  ) {}

  async ngOnInit() {
    const storedTheme = localStorage.getItem('theme');
    if (storedTheme === 'dark') {
      this.isDarkMode = true;
      document.body.classList.add('dark');
    } else {
      this.isDarkMode = false;
      document.body.classList.remove('dark');
    }
    this.auth.onAuthStateChanged(async user => {
      this.user = user;
      if (user) {
        this.loadUserTheme(user.uid);
        this.userProfile = await this.userService.fetchUser(user.uid);
      }
    });
  }

  loadUserTheme(userId: string) {
    this.userService.fetchUser(userId).then(userData => {
      if (!localStorage.getItem('theme')) {
        this.isDarkMode = userData.theme === 'dark';
        document.body.classList.toggle('dark', this.isDarkMode);
      }
    }).catch(error => {
      console.error('Error loading user theme:', error);
    });
  }

  saveUserTheme(userId: string, theme: string) {
    this.userService.saveUserTheme(userId, theme).then(() => {
    }).catch(error => {
      console.error('Error saving user theme:', error);
    });
  }

toggleDarkMode() {
  this.isDarkMode = !this.isDarkMode;
  document.body.classList.toggle('dark', this.isDarkMode);
  localStorage.setItem('theme', this.isDarkMode ? 'dark' : 'light');
  if (this.user) {
    this.saveUserTheme(this.user.uid, this.isDarkMode ? 'dark' : 'light');
  }
}
  toggleDropdown() {
    this.dropdownOpen = !this.dropdownOpen;
  }

  handleLogout(): void {
    this.authService.logout().then(() => {
      this.router.navigate(['/']);
    }).catch((error) => {
      console.error('Logout failed', error);
    });
  }

  navigate(path: string) {
    this.router.navigate([path]);
  }

  openCreateModal() {
    const dialogRef = this.dialog.open(StoryDialogComponent, {
      width: '100vw',
      height: '100vh',
      data: null
    });

    dialogRef.afterClosed().subscribe(result => {
    });
  }
}

<mat-toolbar class="bg-white dark:bg-gray-900 shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full flex justify-between items-center">
      <div class="flex-shrink-0">
        <a href="/" class="text-2xl font-bold text-gray-800 dark:text-white">
          Novel App
        </a>
      </div>
      <div class="flex items-center gap-4">
        <ng-container *ngIf="user; else guestMenu">
          <button
            mat-button
            (click)="openCreateModal()"
            class="hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white dark:focus:ring-gray-600 rounded px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-800 dark:text-white"
          >
          <span class=" text-gray-800 dark:text-white">Post</span>
          </button>
          <a routerLink="/messages" routerLinkActive="text-blue-500" class="flex flex-col items-center hover:text-blue-500 text-gray-800 dark:text-white relative">
            <i class="fas fa-envelope text-2xl mr-2"></i>
            <span
              *ngIf="unreadMessages > 0"
              class="absolute -top-2 -right-2 bg-blue-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center">
              {{ unreadMessages }}
            </span>
          </a>
          <a routerLink="/notifications" routerLinkActive="text-blue-500" class="flex flex-col items-center hover:text-blue-500 text-gray-800 dark:text-white relative">
            <i class="fas fa-bell text-2xl"></i>
            <span
              *ngIf="unreadNotifications > 0"
              class="absolute -top-2 -right-2 bg-blue-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center">
              {{ unreadNotifications }}
            </span>
          </a>
          <button
            mat-button
            [matMenuTriggerFor]="accountMenu"
            class="flex items-center gap-2 text-gray-800 dark:text-white"
          >
            <i class="fas fa-user h-5 w-5 text-gray-800 dark:text-white"></i>
            <span class="hidden sm:inline text-gray-800 dark:text-white">Account</span>
          </button>
          <mat-menu #accountMenu="matMenu" class="bg-white dark:bg-gray-800">
            <button mat-menu-item disabled *ngIf="userProfile">
                <span class="font-medium text-gray-700 dark:text-white">{{ userProfile.username }}</span>
            </button>
            <button mat-menu-item (click)="navigate('/profile')">
              <i class="fas fa-id-badge mr-2 text-gray-800 dark:text-white"></i> <span class="text-gray-800 dark:text-white">Profile</span>
            </button>
            <button mat-menu-item (click)="navigate('/settings')">
              <i class="fas fa-gear mr-2 text-gray-800 dark:text-white"></i> <span class="text-gray-800 dark:text-white">Settings</span>
            </button>
            <button mat-menu-item (click)="handleLogout()">
              <i class="fas fa-sign-out-alt mr-2 text-gray-800 dark:text-white"></i> <span class=" text-gray-800 dark:text-white">Log Out</span>
            </button>
          </mat-menu>
        </ng-container>
        <ng-template #guestMenu>
          <button
            mat-button
            [matMenuTriggerFor]="guestActionsMenu"
            class="flex items-center gap-2 text-gray-800 dark:text-white"
          >
            <i class="fas fa-user h-5 w-5 text-gray-800 dark:text-white"></i>
            <span class="hidden sm:inline dark:text-white">Account</span>
          </button>
          <mat-menu #guestActionsMenu="matMenu" class="bg-white dark:bg-gray-800">
            <button mat-menu-item (click)="navigate('/login')">
              <i class="fas fa-sign-in-alt mr-2 text-gray-800 dark:text-white"></i> <span class=" text-gray-800 dark:text-white">Login</span>
            </button>
            <button mat-menu-item (click)="navigate('/signup')">
              <i class="fas fa-user-plus mr-2 text-gray-800 dark:text-white"></i> <span class=" text-gray-800 dark:text-white">Sign Up</span>
            </button>
          </mat-menu>
        </ng-template>
        <button
          mat-icon-button
          (click)="toggleDarkMode()"
          class="hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white dark:focus:ring-gray-600 rounded-full"
        >
          <mat-icon *ngIf="isDarkMode" class="w-5 h-5 text-gray-800 dark:text-white">sunny</mat-icon>
          <mat-icon *ngIf="!isDarkMode" class="w-5 h-5 text-gray-800 dark:text-white">nightlight</mat-icon>
        </button>
      </div>
    </div>
  </mat-toolbar>

// app/components/header.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';
import { useAuth } from '../hooks/useAuth';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { User } from 'lucide-react';
import { Moon, Sun } from 'lucide-react';

const Header = () => {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const user = useAuth();
  const navigate = useNavigate();

  const handleLogout = async () => {
    try {
      await signOut(auth);
      navigate('/');
    } catch (error) {
      console.error('Error signing out:', error);
    }
  };

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme) {
      const isDark = savedTheme === 'dark';
      setIsDarkMode(isDark);
      document.body.classList.toggle('dark', isDark);
    }

    if (user?.theme) {
      const isDark = user.theme === 'dark';
      setIsDarkMode(isDark);
      document.body.classList.toggle('dark', isDark);
      localStorage.setItem('theme', user.theme);
    }
  }, [user]);

  const toggleDarkMode = async () => {
    const newTheme = isDarkMode ? 'light' : 'dark';
    setIsDarkMode(!isDarkMode);
    document.body.classList.toggle('dark');
    if (user) {
      await fetch(`http://localhost:5000/api/users/${user.uid}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ theme: newTheme }),
      });
    }
    localStorage.setItem('theme', newTheme);
    if (newTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  return (
    <header className={`bg-white dark:bg-gray-900 shadow-md ${isDarkMode ? 'dark' : ''}`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex-shrink-0">
            <a href="/" className="text-2xl font-bold text-gray-800 dark:text-white">
              Novel App
            </a>
          </div>

          <div className="flex items-center gap-4">
            <Button
              variant="outline"
              onClick={() => navigate('/create-story')}
              className="hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white dark:focus:ring-gray-600"
              >
              Post
            </Button>
            {user ? (
              <>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" className="flex items-center gap-2">
                      <User className="h-5 w-5" />
                      <span className="hidden sm:inline">Account</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-48 bg-white dark:bg-gray-800 rounded-md shadow-sm">
                    <DropdownMenuItem className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">
                      <p className="text-gray-600 dark:text-gray-300">
                        Logged in as: <span className="font-medium">{user.email}</span>
                      </p>
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={handleLogout} className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">
                      Log Out
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </>
            ) : (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" className="flex items-center gap-2">
                    <User className="h-5 w-5" />
                    <span className="hidden sm:inline">Account</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48 bg-white dark:bg-gray-800 rounded-md shadow-sm">
                  <DropdownMenuItem onClick={() => navigate('/login')} className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">
                    Login
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => navigate('/signup')} className="px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">
                    Sign Up
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            )}
            <button
              onClick={toggleDarkMode}
              className="flex items-center hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white dark:focus:ring-gray-600 rounded-full p-2"
            >
              {isDarkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </div>
    </header>
  );
};
export default Header;
