// app/routes/storyDetails.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import type { Story } from '../types/story';
import { useNavigate } from 'react-router-dom';

const StoryDetails = () => {
  const { storyId } = useParams();
  const [story, setStory] = useState<Story | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchStory = async () => {
      try {
        const response = await fetch(`http://localhost:5000/api/stories/${storyId}`);
        if (response.ok) {
          const data = await response.json();
          setStory(data);
        } else {
          navigate('/not-found');
          console.error('Error fetching story:', response.statusText);
        }
      } catch (error) {
        console.error('Error fetching story:', error);
      }
    };

    fetchStory();
  }, [storyId, navigate]); // Add navigate to the dependency array

  if (!story) {
    return (
      <div className="flex items-center justify-center h-screen">
        <p className="text-lg">Loading...</p>
      </div>
    );
  }


  return (
    <div className="container mx-auto p-4 text-center"> 
      <h1 className="text-3xl font-bold mb-4">{story.title}</h1>
      <h3 className="text-xl font-semibold mb-2">Summary:</h3>
      <p className="text-lg mb-4">{story.summary}</p>

      <div className="flex flex-col space-y-2">
        <h3 className="text-xl font-semibold">Genres:</h3>
        <ul className="list-disc ml-4">
          {story.genres.map((genre) => (
            <li key={genre}>{genre}</li>
          ))}
        </ul>
      </div>

      <div className="flex flex-col space-y-2">
        <h3 className="text-xl font-semibold">Rating:</h3>
        <p>{story.rating}</p>
      </div>

      <div className="flex flex-col space-y-2">
        <h3 className="text-xl font-semibold">Tags:</h3>
        <ul className="list-disc ml-4">
          {story.tags.map((tag) => (
            <p key={tag}>{tag}</p>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default StoryDetails;

// src/app/story-details/story-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { StoryService } from 'src/app/services/story.service';
import { Auth, onAuthStateChanged, User } from '@angular/fire/auth';
import { MatDialog } from '@angular/material/dialog';
import { StoryDialogComponent } from '../components/story-dialog/story-dialog.component';

@Component({
  selector: 'app-story-details',
  templateUrl: './story-details.component.html',
})
export class StoryDetailsComponent implements OnInit {
  story: any = null;
  isAuthor: boolean = false;

  constructor(
    private route: ActivatedRoute,
    private storyService: StoryService,
    private router: Router,
    private auth: Auth,
    private dialog: MatDialog,
  ) {}

  async ngOnInit() {
    const storyId = this.route.snapshot.paramMap.get('storyId');
    if (storyId) {
      await this.fetchStory(storyId);
      this.checkCurrentUser();
    }
  }
  checkCurrentUser() {
    onAuthStateChanged(this.auth, (user: User | null) => {
      if (user) {
        this.isAuthor = user.uid === this.story?.author.id;
      } else {
        this.isAuthor = false;
      }
    });
  }
  async fetchStory(storyId: string) {
    try {
      const storyData = await this.storyService.getStoryById(storyId);
      const authorData = await this.storyService.fetchUser(storyData.author);

      this.story = { ...storyData, author: authorData };
    } catch (error) {
      console.error('Error fetching story:', error);
      this.router.navigate(['/not-found']);
    }
  }

  openEditModal(story: any) {
    const dialogRef = this.dialog.open(StoryDialogComponent, {
      width: '100vw',
      height: '100vh',
      data: story,
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        console.log('Story Edited:', result);
      }
    });
  }
}

<div *ngIf="!story" class="flex justify-center h-screen bg-gray-100 pt-4 dark:bg-gray-800">
    <div class="flex flex-col items-center w-full max-w-lg space-y-4 animate-pulse">
      <div class="w-full h-12 bg-gray-300 rounded dark:bg-gray-700"></div>
      <div class="w-3/4 h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
      <div class="w-full h-48 bg-gray-300 rounded-lg dark:bg-gray-700"></div>
      <div class="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
      <div class="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
    </div>
  </div>
  
  <div *ngIf="story" class="container mx-auto p-4 text-center">
    <h1 class="text-3xl font-bold mb-4">{{ story.title }}</h1>
    <h3 class="text-xl font-semibold mb-2">Author: {{ story.author.username }}</h3>
    <h3 class="text-xl font-semibold mb-2">Summary:</h3>
    <p class="text-lg mb-4">{{ story.summary }}</p>
  
    <div class="flex flex-col space-y-2 pb-4">
      <h3 class="text-xl font-semibold">Rating:</h3>
      <p>{{ story.rating }}</p>
    </div>
  
    <div class="flex flex-col space-y-2 pb-4">
      <h3 class="text-xl font-semibold">Tags:</h3>
      <p>{{ story.tags.join(', ') }}</p>
    </div>
  
    <button
      *ngIf="isAuthor"
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
      (click)="openEditModal(story)"
    >
      Edit Story
    </button>
  </div>
