// src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
})
export class LoginComponent {
  email: string = '';
  password: string = '';
  loginError: string = '';
  loginSuccess: string = '';

  constructor(
    private authService: AuthService,
    private router: Router,
  ) {}

  login() {
    this.authService
      .signIn(this.email, this.password)
      .then(() => {
        this.loginSuccess = 'Login successful!';
        setTimeout(() => {
          this.router.navigate(['/home']);
        }, 1000);
      })
      .catch((error) => {
        this.loginError = error.message;
      });
  }
}

<div class="flex items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-800">
  <div class="bg-white dark:bg-gray-900 shadow-lg rounded-lg p-8 w-full max-w-md">
    <h1 class="text-3xl font-bold text-center text-gray-800 dark:text-white mb-6">Login</h1>
    <form (ngSubmit)="login()" class="space-y-6 dark:border-gray-700 dark:text-white">
      <mat-form-field appearance="outline" class="w-full dark:text-white">
        <mat-label class="placeholder">Email</mat-label>
        <input matInput [(ngModel)]="email" name="email" type="email" required 
          class="w-full p-3 mt-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white" />
      </mat-form-field>
      
      <mat-form-field appearance="outline" class="w-full">
        <mat-label class="placeholder">Password</mat-label>
        <input matInput [(ngModel)]="password" name="password" type="password" required 
          class="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-700 dark:text-white" />
      </mat-form-field>
  
      <div *ngIf="loginError" class="text-red-500 text-center mt-2">
        {{ loginError }}
      </div>
      <div *ngIf="loginSuccess" class="text-green-500 text-center mt-2">
        {{ loginSuccess }}
      </div>
  
      <button mat-raised-button color="primary" class="w-full py-3 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" type="submit">
        Log In
      </button>
    </form>
  
    <div class="text-center mt-4">
      <p class="text-sm text-gray-600 dark:text-gray-300">
        Don't have an account? 
        <a [routerLink]="'/signup'" class="text-blue-500 hover:underline">Sign up here</a>
      </p>
    </div>
  </div>
</div>

// app/routes/login.tsx
import React, { useState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "../../firebase";
import { useNavigate } from "react-router-dom";

export default function Login() {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [success, setSuccess] = useState<string>("");
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await signInWithEmailAndPassword(auth, email, password);
      setSuccess("Login successful!");
      setEmail("");
      setPassword("");
      navigate("/");
    } catch (error: any) {
        console.error("Error during login:", error.code, error.message);
        if (error.code === "auth/invalid-credential") {
          setError("Invalid credentials. Please check your email and password.");
        } else {
            setError("Login failed! Please check your credentials.");
        }
      }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-800">
      <div className="bg-white dark:bg-gray-900 shadow-lg rounded-lg p-8 w-full max-w-md">
        <h2 className="text-3xl font-bold text-center text-gray-800 dark:text-white mb-6">Login</h2>
        <form onSubmit={handleLogin} className="space-y-6">
          <div>
            <label htmlFor="email" className="block text-gray-700 dark:text-gray-300">Email</label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-white"
              required
            />
          </div>
          <div>
            <label htmlFor="password" className="block text-gray-700 dark:text-gray-300">Password</label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-white"
              required
            />
          </div>
          {error && (
            <div className="text-red-500 text-center mt-2">
              {error}
            </div>
          )}
          {success && (
            <div className="text-green-500 text-center mt-2">
            {success}
            </div>
          )}
          <button
            type="submit"
            className="w-full py-3 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            Log In
          </button>
        </form>
        <div className="text-center mt-4">
          <p className="text-gray-600 dark:text-gray-300">Don't have an account? <a href="/signup" className="text-blue-500 hover:underline">Sign Up</a></p>
        </div>
      </div>
    </div>
  );
};
