// src/app/components/signup/signup.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
})
export class SignupComponent {
  email: string = '';
  password: string = '';
  signupError: string = '';

  constructor(
    private authService: AuthService,
    private router: Router,
    private userService: UserService,
  ) {}

  async signup() {
    try {
      const user = await this.authService.signUp(this.email, this.password);
      if (user) {
        this.router.navigate(['/']);
      } else {
        throw new Error('User is null');
      }
    } catch (error) {
      console.log('Error signing up:', error);
      this.signupError = (error as any).message;
    }
  }
}

<div class="flex items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-800">
  <div class="bg-white dark:bg-gray-900 shadow-lg rounded-lg p-8 w-full max-w-md">
    <h1 class="text-3xl font-bold text-center text-gray-800 dark:text-white mb-6">Sign Up</h1>
    <form (ngSubmit)="signup()" class="space-y-6 dark:border-gray-700 dark:text-white">
      
      <mat-form-field appearance="outline" class="w-full dark:text-white">
        <mat-label class="placeholder">Email</mat-label>
        <input matInput [(ngModel)]="email" name="email" type="email" required 
          class="w-full p-3 mt-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white" />
      </mat-form-field>
      
      <mat-form-field appearance="outline" class="w-full">
        <mat-label class="placeholder">Password</mat-label>
        <input matInput [(ngModel)]="password" name="password" type="password" required 
          class="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:border-gray-700 dark:text-white" />
      </mat-form-field>
  
      <div *ngIf="signupError" class="text-red-500 text-center mt-2">
        {{ signupError }}
      </div>
  
      <button mat-raised-button color="primary" class="w-full py-3 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500" type="submit">
        Sign Up
      </button>
    </form>
  
    <div class="text-center mt-4">
      <p class="text-sm text-gray-600 dark:text-gray-300">
        Already have an account? 
        <a [routerLink]="'/login'" class="text-blue-500 hover:underline">Log in here</a>
      </p>
    </div>
  </div>
</div>

// app/routes/signup.tsx
import React, { useState } from "react";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { auth } from "../../firebase";
import { useNavigate } from "react-router-dom";

export default function Signup() {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [success, setSuccess] = useState<string>("");
  const navigate = useNavigate();

  const handleSignup = async (e: React.FormEvent) => {
    e.preventDefault();
    if (password !== confirmPassword) {
        setError("Passwords do not match. Please try again.");
        return;
    }
    try {
      await createUserWithEmailAndPassword(auth, email, password);
      setSuccess("Signup successful! Please log in.");
      setEmail("");
      setPassword("");
      setConfirmPassword("");
      navigate("/");
    } catch (error: any) {
        if (error.code === "auth/email-already-in-use") {
            setError("Email already in use. Please try another email.");
            return;
        } else if (error.code === "auth/weak-password") {
            setError("Password is too weak. It should be at least 6 characters.");
            return;
        } else {
            console.error("Error during signup:", error.code, error.message);
            setError("Signup failed! Please check your inputs.");
        }
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-800">
      <div className="bg-white dark:bg-gray-900 shadow-lg rounded-lg p-8 w-full max-w-md">
        <h2 className="text-3xl font-bold text-center text-gray-800 dark:text-white mb-6">Sign Up</h2>
        <form onSubmit={handleSignup} className="space-y-6">
          <div>
            <label htmlFor="email" className="block text-gray-700 dark:text-gray-300">Email</label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-white"
              required
            />
          </div>
          <div>
            <label htmlFor="password" className="block text-gray-700 dark:text-gray-300">Password</label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-white"
              required
            />
          </div>
          <div>
            <label htmlFor="confirmPassword" className="block text-gray-700 dark:text-gray-300">Confirm Password</label>
            <input
              type="password"
              id="confirmPassword"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              className="w-full p-3 mt-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:text-white"
              required
            />
          </div>
          {error && (
            <div className="text-red-500 text-center mt-2">
              {error}
            </div>
          )}
          <button
            type="submit"
            className="w-full py-3 bg-blue-500 text-white font-semibold rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            Sign Up
          </button>
        </form>
        <div className="text-center mt-4">
          <p className="text-gray-600 dark:text-gray-300">Already have an account? <a href="/login" className="text-blue-500 hover:underline">Log In</a></p>
        </div>
      </div>
    </div>
  );
};
