// app/routes/story/story-details.tsx
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import type { Story } from '../../types/story';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';

const StoryDetails = () => {
  const { storyId } = useParams();
  const [story, setStory] = useState<Story | null>(null);
  const navigate = useNavigate();
  const user = useAuth();

  useEffect(() => {
    const fetchStory = async () => {
      try {
        const response = await fetch(`http://localhost:5000/api/stories/${storyId}`);
        if (response.ok) {
          const data = await response.json();
          const author = await fetchAuthor(data.author);
          setStory({ ...data, author: author });
        } else {
          navigate('/not-found');
        }
      } catch (error) {
        console.error('Error fetching story:', error);
      }
    };

    fetchStory();
  }, [storyId, navigate]);

  if (!story) {
    return (
      <div className="flex justify-center h-screen bg-gray-100 pt-4 dark:bg-gray-800">
      <div className="flex flex-col items-center w-full max-w-lg space-y-4 animate-pulse">
        <div className="w-full h-12 bg-gray-300 rounded dark:bg-gray-700"></div>
        <div className="w-3/4 h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
        <div className="w-full h-48 bg-gray-300 rounded-lg dark:bg-gray-700"></div>
        <div className="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
        <div className="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
      </div>
    </div>
    
    );
  }

  const isAuthor = user?.uid === story.author.id; 

  return (
    <div className="container mx-auto p-4 text-center"> 
      <h1 className="text-3xl font-bold mb-4">{story.title}</h1>
      <h3 className="text-xl font-semibold mb-2">Author: {story.author.username }</h3>
      <h3 className="text-xl font-semibold mb-2">Summary:</h3>
      <p className="text-lg mb-4">{story.summary}</p>

      <div className="flex flex-col space-y-2 pb-4">
        <h3 className="text-xl font-semibold">Rating:</h3>
        <p>{story.rating}</p>
      </div>

      <div className="flex flex-col space-y-2 pb-4">
        <h3 className="text-xl font-semibold">Tags:</h3>
        <ul className="list-disc ml-4">
          {story.tags.map((tag) => (
            <p key={tag}>{tag}</p>
          ))}
        </ul>
      </div>
      {isAuthor && (
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          onClick={() => navigate(`/stories/${story._id}/edit`)} 
        >
          Edit Story
        </button>
      )}
    </div>
  );
};

const fetchAuthor = async (authorId: string) => {
  try {
    const response = await fetch(`http://localhost:5000/api/users/${authorId}`);
    if (response.ok) {
      const data = await response.json();
      return data;
    } else {
      console.error('The api did not return a valid response');
      return '';
    }
  } catch (error) {
    console.error('Error fetching username:', error);
    return '';
  }
};

export default StoryDetails;

// src/app/pages/story-details/story-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { StoryService } from 'src/app/services/story.service';
import { Auth, onAuthStateChanged, User } from '@angular/fire/auth';
import { MatDialog } from '@angular/material/dialog';
import { StoryDialogComponent } from '../../components/story-dialog/story-dialog.component';
import { ChapterDialogComponent } from '../../components/chapter-dialog/chapter-dialog.component';
import { ChapterService } from 'src/app/services/chapter.service';

@Component({
  selector: 'app-story-details',
  templateUrl: './story-details.component.html',
})
export class StoryDetailsComponent implements OnInit {
  story: any = null;
  isAuthor: boolean = false;
  isLoading: boolean = true;

  constructor(
    private route: ActivatedRoute,
    private storyService: StoryService,
    private router: Router,
    private auth: Auth,
    private dialog: MatDialog,
    private chapterService: ChapterService,
  ) {}

  async ngOnInit() {
    const storyId = this.route.snapshot.paramMap.get('storyId');
    if (storyId) {
      await this.fetchStory(storyId);
      await this.fetchStoryChapters(storyId);
      this.checkCurrentUser();
    }
  }
  checkCurrentUser() {
    onAuthStateChanged(this.auth, (user: User | null) => {
      if (user) {
        this.isAuthor = user.uid === this.story?.author.id;
        this.isLoading = false;
      } else {
        this.isAuthor = false;
        this.isLoading = false;
      }
    });
  }
  async fetchStory(storyId: string) {
    try {
      const storyData = await this.storyService.getStoryById(storyId);
      this.story = { ...storyData };
    } catch (error) {
      console.error('Error fetching story:', error);
      this.router.navigate(['/not-found']);
    }
  }

  async fetchStoryChapters(storyId: string) {
    try {
      const chaptersData = await this.chapterService.getChaptersByStoryId(storyId);
      this.story = { ...this.story, chapters: chaptersData };
    } catch (error) {
      console.error('Error fetching story:', error);
      this.router.navigate(['/not-found']);
    }
  }

  openEditModal(story: any) {
    const dialogRef = this.dialog.open(StoryDialogComponent, {
      width: '100vw',
      height: '100vh',
      data: story,
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        console.log('Story Edited:', result);
      }
    });
  }

  openChapterModal(storyId: string, chapterId?: string) {
    let dialogData: any = { storyId };  
    if (chapterId) {
      dialogData._id = chapterId;
    }
  
    const dialogRef = this.dialog.open(ChapterDialogComponent, {
      width: '100vw',
      height: '100vh',
      data: dialogData
    });
  
    dialogRef.afterClosed().subscribe(result => {
      console.log('Dialog closed', result);
    });
  }

  onChapterSelect(event: Event): void {
    const selectElement = event.target as HTMLSelectElement;
    const chapterId = selectElement.value;
    if (chapterId) {
      this.router.navigate(['/chapters', chapterId]);
    }
  }
}

<div *ngIf="isLoading" class="flex justify-center h-screen bg-gray-100 pt-4 dark:bg-gray-800">
  <div class="flex flex-col items-center w-full max-w-lg space-y-4 animate-pulse">
    <div class="w-full h-12 bg-gray-300 rounded dark:bg-gray-700"></div>
    <div class="w-3/4 h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
    <div class="w-full h-48 bg-gray-300 rounded-lg dark:bg-gray-700"></div>
    <div class="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
    <div class="w-full h-4 bg-gray-300 rounded dark:bg-gray-700"></div>
  </div>
</div>

<div *ngIf="story" class="container mx-auto p-4 text-center">
  <h1 class="text-3xl font-bold mb-4 text-blue-500">{{ story.title }}</h1>
  <p class="text-lg mb-2">By: <span class="font-semibold">{{ story.author.username }}</span></p>

  <div *ngIf="!isAuthor" class="flex items-center mb-4">
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2">
      Subscribe
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded">
      Like
    </button>
  </div>

  <div class="mb-4">
    <p class="text-gray-600">{{ story.summary }}</p>
  </div>

  <div class="flex flex-col"> 
    <h2 class="text-xl font-semibold mb-2">Chapters</h2>
    <div class="relative inline-block w-full">
      <select (change)="onChapterSelect($event)"
      class="dark:text-black dark:bg-gray-300 border rounded py-2 px-3 focus:outline-none focus:ring-blue-500 focus:ring-opacity-50">
        <option disabled value="" class="dark: text-black">Select Chapter</option>
        <option *ngFor="let chapter of story.chapters" [value]="chapter._id">
          Chapter {{ chapter.chapter }}: {{ chapter.title }}
        </option>
      </select>
    </div>
  </div>

  <div class="flex justify-center"> 
    <div class="text-center">
      <h2 class="text-xl font-semibold mb-2">Tags</h2>
      <div class="flex flex-wrap gap-2 justify-center">
        <span class="bg-gray-200 text-gray-700 px-2 py-1 rounded-md" *ngFor="let tag of story.tags">
          {{ tag }}
        </span>
      </div>
    </div>
  </div>
  

  <div *ngIf="isAuthor" class="mt-4">
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4" (click)="openEditModal(story)">
      Edit Story
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded" (click)="openChapterModal(story._id)">
      Add Chapter
    </button>
  </div>
</div>
